urls:
  contact:
    contact: "https://www.railstutorial.org/contact"
  footer:
    tutorial: "https://www.railstutorial.org/"
    author: "https://www.michaelhartl.com/"
    news: "https://news.railstutorial.org/"
  help:
    help: "https://www.railstutorial.org/help"
    book: "https://www.railstutorial.org/book"
  about:
    learn_enough: "https://www.learnenough.com/"
    book: "https://www.railstutorial.org/book"
    series: "https://screencasts.railstutorial.org/"
    ruby: "https://rubyonrails.org/"
